### ISSUE TITLE
Incorrect heading levels in install documentation

### ISSUE THREAD

**Issue by cyrozap** [newaetech/phywhispererusb#13]
It's not that big of an issue, but it did confuse me for a moment so I figure I'd mention it:

On the [installation page](https://phywhispererusb.readthedocs.io/en/latest/installing.html) of the documentation, the OS-specific prerequisite installation sections are not nested under the "Prerequisites" heading, and the "Installing PhyWhisperer" heading is nested only under the "Mac OS X" prerequisites section instead of under the main "Installation" heading.

I'd fix this myself, but I wasn't certain if my interpretation of how the headings were supposed to be organized was correct, so I'm posting this as an issue to confirm that.

**Comment by jpcrypt** [comment]
Thank you, fixed!
