### ISSUE TITLE
Missing firmware upgrade instructions

### ISSUE THREAD

**Issue by cyrozap** [newaetech/phywhispererusb#14]
I'd like to update the firmware of my PhyWhisperer-USB, but I can't find a list of steps to do that. I can see there's an `auto_program()` function in the API, but there aren't any usage examples (e.g., do I need to do some other initialization beforehand?) and it's unclear that programming the device with "default firmware" will update it to the latest version.

**Comment by jpcrypt** [comment]
Sorry for ignoring this for so long! `auto_program()` is indeed the way to update to the latest version; the documentation has been updated.
