### ISSUE TITLE
continuous realtime sniffing 

### ISSUE THREAD

**Issue by nitrogar** [newaetech/phywhispererusb#19]
i search online and through the API documentation and code, but could not figure out how to stream the usb packets directly to the host without queuing them in the FIFO.

the FIFO is small for my use case and I always get :

WARNING:root:FIFO overflowed, capture stopped.
WARNING:root:1878315 entries captured.

so is there a way to just stream the packets directly without storing them or an API to clear the FIFIO periodically 

thanks for the great project.

**Comment by jpcrypt** [comment]
Unfortunately no. Even in streaming mode, captured data needs to go through the FPGA's FIFO. If the rate of captured data exceeds the transfer rate that we can sustain over the USB link, there is potential for overflow.

**Comment by colinoflynn** [comment]
Depending on what you are capturing, if you can change the configuration to reduce the packet flow rate the PhyWhisperer might be able to "keep up" with the host emptying the FIFO in a loop. Nothing inherently prevents you from doing this, just that if the USB traffic is too bursty it will overflow the FIFO.

If you didn't see, there is a [demonstration notebook](https://github.com/newaetech/phywhispererusb/blob/master/software/jupyter/stream.ipynb).
